#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
# application="pimpleFoam"

# Run in parallel
# runApplication $application

# make a temp paraview file
# touch "./channelturbTP.foam"

rm -rf log*
rm -rf err*
rm -rf 0.*
rm -rf [1-9]*
rm -rf out*
rm -rf proc*
rm -rf constant/turbModelBackup
